### ISSUE TITLE
Error: 'Invalid SPARQL endpoint' when querying NTA

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-catalog#106]
If I execute the query underneath via the [NoT's API](https://termennetwerk-api.netwerkdigitaalerfgoed.nl/graphiql)...

```graphql
query {
  terms(sources: ["http://data.bibliotheken.nl/thesp/sparql"], query: "Avegaart-van Gogh, Joke") {
    result {
      __typename
      ... on Terms {
        terms {
          uri
          prefLabel
        }
      }
      ... on Error {
        message
      }
    }
  }
}
```

then an error is returned: `Invalid SPARQL endpoint response from http://data.bibliotheken.nl/sparql (...)`.

However, this query (without the comma in `query`) does return results:

```graphql
query {
  terms(sources: ["http://data.bibliotheken.nl/thesp/sparql"], query: "Avegaart-van Gogh Joke") {
    result {
      __typename
      ... on Terms {
        terms {
          uri
          prefLabel
        }
      }
      ... on Error {
        message
      }
    }
  }
}
```

If I directly execute the underlying SPARQL query on the [KB's endpoint](http://data.bibliotheken.nl/sparql), then the first query yields results:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?rdfs_label ;
        skos:altLabel ?schema_name ;
        skos:altLabel ?schema_alternateName ;
        skos:scopeNote ?schema_description .
}
WHERE {
    ?uri schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/persons> .
    ?uri ?predicate ?label .
    VALUES ?predicate { rdfs:label schema:name schema:alternateName }

    # Replace query "A B" with "A AND B", leaving queries "A AND B" or "A OR B" unchanged.
    FILTER (<bif:contains> (?label,
        REPLACE(
            REPLACE("Avegaart-van Gogh, Joke", "[.,]", " "),
            "(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)(?!$)(?![[:space:]])",
            " AND ",
            "i"
        )
    ))

    OPTIONAL { ?uri rdfs:label ?rdfs_label }
    OPTIONAL { ?uri schema:name ?schema_name }
    OPTIONAL { ?uri schema:alternateName ?schema_alternateName }
    OPTIONAL { ?uri schema:description ?schema_description }
}
LIMIT 1000
```

What could be an explanation for this?

**Comment by ddeboer** [comment]
I get this error message from the app on master:

`
Invalid SPARQL endpoint response from http://data.bibliotheken.nl/sparql (HTTP status 500):\nVirtuoso 37000 Error XM029: Free-text expression, line 1: syntax error at ,\n\n\nSPARQL query:\ndefine output:format \"HTTP+TTL text/turtle\" CONSTRUCT {\n  ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept>.\n  ?uri <http://www.w3.org/2004/02/skos/core#prefLabel> ?rdfs_label.\n  ?uri <http://www.w3.org/2004/02/skos/core#altLabel> ?schema_name.\n  ?uri <http://www.w3.org/2004/02/skos/core#altLabel> ?schema_alternateName.\n  ?uri <http://www.w3.org/2004/02/skos/core#scopeNote> ?schema_description.\n}\nWHERE {\n  {\n    ?uri <http://schema.org/mainEntityOfPage> ?var0.\n    ?var0 <http://schema.org/isPartOf> <http://data.bibliotheken.nl/id/dataset/persons>.\n    ?uri ?predicate ?label.\n    VALUES ?predicate {\n      <http://www.w3.org/2000/01/rdf-schema#label>\n      <http://schema.org/name>\n      <http://schema.org/alternateName>\n    }\n    OPTIONAL { ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?rdfs_label. }\n    OPTIONAL { ?uri <http://schema.org/name> ?schema_name. }\n    OPTIONAL { ?uri <http://schema.org/alternateName> ?schema_alternateName. }\n    OPTIONAL { ?uri <http://schema.org/description> ?schema_description. }\n    FILTER(<bif:contains>(?label, REPLACE(\"Avegaart-van Gogh, Joke\", \"(?<!AND)(?<!OR)[[:space:]]+(?!AND)(?!OR)\", \" AND \", \"i\")))\n  }\n}\nLIMIT 1000
`

In that query the `REPLACE("Avegaart-van Gogh, Joke", "[.,]", " "),` from the query you’re executing at the SPARQL endpoint is missing. Are you perhaps comparing two different versions of the query?

**Comment by EnnoMeijers** [comment]
I agree, it looks like the public api is not up to date.

**Comment by sdevalk** [comment]
Ouch, very true! Changes to the catalog aren't merged into the API automatically. Issue solved - closing.
