### ISSUE TITLE
Filter language for prefLabel

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-catalog#109]
Currently all language variations for the prefLabel seem to be presented which leads to strange behavior, see http://data.bibliotheken.nl/id/thes/p06854796X where the Chinese(?) label is presented first. At least for the prefLabel, which is being used as title, I would suggest to filter on the language label.

**Comment by ddeboer** [comment]
Moved this issue from the demo to the catalog repository because it’s not related to the demonstrator.

**Comment by EnnoMeijers** [comment]
I really meant this as a user interface issue. I think it legitimate for the api to return multiple languages for prefLabel. It could be a choice in the UI to show only a preferred language (maybe even aligned to a language switch in the interface?).

**Comment by ddeboer** [comment]
Fair enough! Unfortunately, http://data.bibliotheken.nl/doc/thes/p06854796X.json does not return the language of the prefLabel, so this is a no-go.

**Comment by EnnoMeijers** [comment]
Right, this is an error on the KB's end, so in this case we are not able to distinguish between the language variants and currently we do language filtering only in the queries. In order to support have multi language support in the front-end in the future we should think about the best way to approach this more clearly. I will close this issue for now.
