### ISSUE TITLE
Add "STCN drukkersthesaurus"

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/network-of-terms-catalog#126]
A PICA Verbonden Erfgoed project wants to link their data with the "STCN drukkersthesaurus", via the network of terms.

According to @renevoorburg this data is part of the STCN-dataset provided via data.bibliotheken.nl. It's planned to offer this set also as separate dataset.

To [query](http://data.bibliotheken.nl/sparql?default-graph-uri=&qtxt=select+distinct(%3Fuitgever)+where+{%0D%0A++%23+we+beperken+ons+tot+de+STCN%3A%0D%0A++%3Fs+foaf%3AisPrimaryTopicOf%2Fvoid%3AinDataset+%3Chttp%3A%2F%2Fdata.bibliotheken.nl%2Fid%2Fdataset%2Fstcn%3E+.%0D%0A++%23+we+zoeken+de+uitgever%3A%0D%0A++%3Fs+schema%3Apublication%2Fschema%3ApublishedBy+%3Fuitgever+.+%0D%0A}%0D%0A&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) the "STCN drukkersthesaurus": 
```
select distinct(?uitgever) where {
  # we beperken ons tot de STCN:
  ?s foaf:isPrimaryTopicOf/void:inDataset <http://data.bibliotheken.nl/id/dataset/stcn> .
  # we zoeken de uitgever:
  ?s schema:publication/schema:publishedBy ?uitgever . 
}
```
PS. This query will change somewhere in the future (`foaf:isPrimaryTopicOf/void:inDataset` will become `schema:mainEntityOfPage/schema:isPartOf`)

**Comment by ddeboer** [comment]
@coret @EnnoMeijers Should we add the whole STCN or the drukkersthesaurus separately? A problem with the latter is that it doesn’t have a URI yet, so we’ll have to invent our own (ugh). Moreover, that URI will change it in the future.

**Comment by renevoorburg** [comment]
Hoi,
De dataset voor de drukkers gaat deze URI krijgen:
http://data.bibliotheken.nl/id/dataset/stcn/printers <http://data.bibliotheken.nl/id/dataset/stcn/printers>
Groet, René

**Comment by ddeboer** [comment]
Thanks @renevoorburg!

@renevoorburg @coret What should be included in this datasets, and how do we make that selection in the SPARQL query? Is a list of printers intended? If so, this seems to do the trick:

```sparql
?s schema:additionalType <http://www.productontology.org/id/Printer_%28publishing%29> .
```

**Comment by renevoorburg** [comment]
That approach wil work.
Eventually (I hope soon) this will be the 'official' approach:


?s schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/stcn/printers <http://data.bibliotheken.nl/id/dataset/stcn/printers>> . }

**Comment by EnnoMeijers** [comment]
I suggest to stick to the "Drukkers thesaurus" for the moment. As long as there is no well defined work level for publications in the KB data (NBT/STCN) we should not add them as a reference source for the Network-of-Terms.
