### ISSUE TITLE
Improve NTA query (nta.rq)

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-catalog#38]
Currently the NTA subset is selected by using the GRAPH identifier, this might lead to problems in the future. A more consistent way of doing this would be to use the following selection:
select * where { ?s schema:mainEntityOfPage/schema:isPartOf <http://data.bibliotheken.nl/id/dataset/persons> . }

**Comment by sdevalk** [comment]
Proposal: https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/issues/38

**Comment by sdevalk** [comment]
Merged into master: https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/commit/e3bebef9e6f76ae3f4d23010880a5a0dc09e377d. Closing
