### ISSUE TITLE
CHT queries ignores matches with altLabels

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-catalog#39]
The current CHT query only finds matches in prefLabels this should be expanded to also match altLabels.

**Comment by sdevalk** [comment]
Good one! I'll change this.

**Comment by sdevalk** [comment]
Proposed fix: https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/pull/40

**Comment by sdevalk** [comment]
Merged into master: https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/commit/fafe441761e84741e5377375fc302f760c0a70ac. Closing.
