### ISSUE TITLE
Sample queries for 'lookup by URI' function

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-catalog#66]
For further discussion. I've created some SPARQL queries for the 'lookup by URI' function that we could add to the API of the NoT. These queries could be used for querying data sources that use the same 'base URI' for their terms.

# Query 1: Data sources of the Koninklijke Bibliotheek
This query combines the queries for Brinkman and NTA into one.

```sparql
# Do not remove this prefix - KB data uses old version of SKOS
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?prefLabel ;
        skos:prefLabel ?rdfs_label ;
        skos:altLabel ?altLabel ;
        skos:altLabel ?schema_alternateName ;
        skos:altLabel ?schema_name ;
        skos:hiddenLabel ?hiddenLabel ;
        skos:scopeNote ?scopeNote ;
        skos:scopeNote ?schema_description ;
        skos:broader ?broader_uri ;
        skos:narrower ?narrower_uri ;
        skos:related ?related_uri .
    ?broader_uri skos:prefLabel ?broader_prefLabel .
    ?narrower_uri skos:prefLabel ?narrower_prefLabel .
    ?related_uri skos:prefLabel ?related_prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    FILTER(?uri IN (<http://data.bibliotheken.nl/id/thes/p06854796X>, <http://data.bibliotheken.nl/id/thes/p317203789>)) .
    OPTIONAL {
        ?uri skos:prefLabel ?prefLabel .
        FILTER(LANG(?prefLabel) = "nl" )
    }
    OPTIONAL {
        ?uri skos:altLabel ?altLabel .
        FILTER(LANG(?altLabel) = "nl")
    }
    OPTIONAL {
        ?uri skos:hiddenLabel ?hiddenLabel .
        FILTER(LANG(?hiddenLabel) = "nl")
    }
    OPTIONAL {
        ?uri skos:scopeNote ?scopeNote .
        FILTER(LANG(?scopeNote) = "nl")
    }
    OPTIONAL {
        ?uri skos:broader ?broader_uri .
        ?broader_uri skos:prefLabel ?broader_prefLabel .
        FILTER(LANG(?broader_prefLabel) = "nl")
    }
    OPTIONAL {
        ?uri skos:narrower ?narrower_uri .
        ?narrower_uri skos:prefLabel ?narrower_prefLabel .
        FILTER(LANG(?narrower_prefLabel) = "nl")
    }
    OPTIONAL {
        ?uri skos:related ?related_uri .
        ?related_uri skos:prefLabel ?related_prefLabel .
        FILTER(LANG(?related_prefLabel) = "nl")
    }
    OPTIONAL { ?uri rdfs:label ?rdfs_label }
    OPTIONAL { ?uri schema:name ?schema_name }
    OPTIONAL { ?uri schema:alternateName ?schema_alternateName }
    OPTIONAL { ?uri schema:description ?schema_description }
}
LIMIT 1000
```

# Query 2: Data sources of Muziekweb
This query combines the queries for 'genres' and 'music groups' into one.

```sparql
PREFIX muziekweb: <https://data.muziekweb.nl/vocab/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?rdfs_label ;
        skos:prefLabel ?prefLabel ;
        skos:altLabel ?altLabel ;
        skos:hiddenLabel ?hiddenLabel ;
        skos:scopeNote ?rdfs_comment ;
        skos:scopeNote ?schema_description .
    ?uri skos:broader ?broader_uri .
    ?broader_uri skos:prefLabel ?broader_prefLabel .
    ?uri skos:narrower ?narrower_uri .
    ?narrower_uri skos:prefLabel ?narrower_prefLabel .
}
WHERE {
    ?uri ?predicate ?label .
    FILTER(?uri IN (<https://data.muziekweb.nl/Link/M00000034333>, <https://data.muziekweb.nl/Link/T00000000050>)) .
    OPTIONAL { ?uri rdfs:label ?rdfs_label }
    OPTIONAL { ?uri skos:prefLabel ?prefLabel }
    OPTIONAL { ?uri skos:altLabel ?altLabel }
    OPTIONAL { ?uri skos:hiddenLabel ?hiddenLabel }
    OPTIONAL { ?uri rdfs:comment ?rdfs_comment }
    OPTIONAL { ?uri schema:description ?schema_description }
    OPTIONAL {
        ?uri skos:broader ?broader_uri .
        ?broader_uri rdfs:label ?broader_prefLabel
    }
    OPTIONAL {
        ?uri skos:narrower ?narrower_uri .
        ?narrower_uri rdfs:label ?narrower_prefLabel
    }
}
LIMIT 1000
```

# Query 3: Data sources of Wikidata
This query combines the queries for 'all', 'persons', 'places' and 'streets' into one.

There is a huge downside to this query: Wikidata performance collapses if you feed this query with more than 1 URI in the `IN` clause (e.g. URIs such as `http://www.wikidata.org/entity/Q2696551` (person), `http://www.wikidata.org/entity/Q727` (place)).

```sparql
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX mwapi: <https://www.mediawiki.org/ontology#API/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

CONSTRUCT {
    ?item a skos:Concept ;
    	skos:prefLabel ?rdfs_label ;
        skos:altLabel ?altLabel ;
    	skos:altLabel ?altLabelStreetName ;
    	skos:scopeNote ?schema_description .
}
WHERE {
    ?item rdfs:label ?rdfs_label .
    FILTER(LANG(?rdfs_label) = "nl")
    FILTER(?item IN (<http://www.wikidata.org/entity/Q19573969>)) .
    OPTIONAL {
        ?item skos:altLabel ?altLabel .
        FILTER(LANG(?altLabel) = "nl")
    }
    OPTIONAL {
        ?item schema:description ?schema_description
        FILTER(LANG(?schema_description) = "nl")
    }
    # Necessary for street names
    OPTIONAL {
        ?item wdt:P276/rdfs:label ?locationName .
        FILTER(LANG(?locationName) = "nl")
    }
    # Necessary for street names
    OPTIONAL {
        ?item wdt:P131/rdfs:label ?administrationName .
        FILTER(LANG(?administrationName) = "nl")
    }
    # Necessary for street names
    BIND(
        COALESCE(
            IF(BOUND(?locationName), CONCAT(?rdfs_label, " (", ?locationName, ")"), 1/0),
            IF(BOUND(?administrationName), CONCAT(?rdfs_label, " (", ?administrationName, ")"), 1/0)
        )
        AS ?altLabelStreetName 
    )
}
LIMIT 1000
```

**Comment by EnnoMeijers** [comment]
Ok, looks good! Two remarks: 
1. In general I wonder if supporting multiple URI look ups makes sense, I can't think of concrete use case for it, why not address the source directly if you want to do automated aggregation of data from multiple URIs. Isn't the primary use cases for URI lookups supporting (manual) UI interactions like a single lookup or browsing over the results? In this scenario multiple URI lookups are not required.   
2. Should we come up with a naming scheme for the queries to make a clear distinction between the strings search query and the URI look up query?

**Comment by sdevalk** [comment]
Thanks!

In response:

> In general I wonder if supporting multiple URI look ups makes sense, I can't think of concrete use case for it, why not address the source directly if you want to do automated aggregation of data from multiple URIs. Isn't the primary use cases for URI lookups supporting (manual) UI interactions like a single lookup or browsing over the results? In this scenario multiple URI lookups are not required.

Agree, the primary use case is supporting UI interactions. A single URI lookup could suffice, but then it's up to the UI client to send multiple URIs in multiple lookup requests to the NoT. Definitely feasible, but the NoT could make this a bit easier and more performant for clients if it allows for multiple URIs in one lookup request.

A sample use case: the metadata of 'De Nachtwacht' has a property 'Depicted persons'. There are some fifteen persons portrayed on the painting, with their own URI (e.g. to Wikidata). If a user application wants to display the data about these persons (such as the name/prefLabel and description/scopeNote) to a collection manager, then the NoT could assist the application by accepting all of these URIs in one lookup rather than fifteen.

> Should we come up with a naming scheme for the queries to make a clear distinction between the strings search query and the URI look up query?

Yes! :) We also have to think about a way to register this information in the catalog. For example, by extending the current `potentialAction` with a `LookupAction`, in addition to the `SearchAction` [1].

[1] https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/blob/master/catalog/datasets/nta.jsonld#L28-L30

**Comment by sdevalk** [comment]
@ddeboer 

My previous Wikidata query is still performing poorly, resulting in timeouts. Even a condensed version:

Endpoint: https://query.wikidata.org/sparql

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?item rdfs:label ?rdfs_label .
    FILTER(?item IN (<http://www.wikidata.org/entity/Q2696551>, <http://www.wikidata.org/entity/Q727>))
}
LIMIT 1000
```

However, if I change the `FILTER ... IN` to `VALUES`, then the performance is much better. For example:

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?item rdfs:label ?rdfs_label .
    VALUES ?item { <http://www.wikidata.org/entity/Q2696551> <http://www.wikidata.org/entity/Q727> }
}
LIMIT 1000
```

I'll check whether the other queries - for the other sources - also play well with this approach.

**Comment by ddeboer** [comment]
Good solution @sdevalk! Actually, it is to be expected that `VALUES` performs better than `FILTER … IN`: if I’m not mistaken to apply the filter, all results must be fetched first. I’m assuming we didn’t have this problem with search operations because `bif:contains` is a special filter that works differently.
