### ISSUE TITLE
AAT: search results also include terms from TGN and ULAN

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-catalog#85]
If I execute the query underneath:

```graphql
query {
  terms(sources: ["http://vocab.getty.edu/aat/sparql"],
        query: "hoorn") {
    source {
      name
    }
    result {
      __typename
      ... on Terms {
        terms {
          uri
          prefLabel
          altLabel
          scopeNote
        }
      }
      ... on Error {
        message
      }
    }
  }
}
```

...then the results consist of terms from the AAT but also from TGN and ULAN (e.g. `http://vocab.getty.edu/tgn/7263257` and `http://vocab.getty.edu/ulan/500005142`). We probably need to add a condition to the [underlying SPARQL query](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/blob/master/catalog/queries/search/aat.rq) for limiting our search to just the AAT.

**Comment by EnnoMeijers** [comment]
The easiest way to do this I think is to require the results to be in the AAT dataset by adding void:inDataset  http://vocab.getty.edu/dataset/aat
